name: Docs

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"
      - "src/lanyard/**"
      - "example/**"
      - "pyproject.toml"
  pull_request:
    branches:
      - master
    paths:
      - "docs/**"
      - "src/lanyard/**"
      - "example/**"
      - "pyproject.toml"

permissions:
    contents: write

jobs:
  docs-gen:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - "3.12"
          - "3.13"

    defaults:
      run:
        shell: bash

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: Install project dependencies
        run: |
          pip install -e ".[docs]"

      - name: Sphinx build
        run: |
          uv run sphinx-build docs/source docs/_build

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          allow_empty_commit: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/_build/
          force_orphan: true