name: Tests

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/tests.yaml"
      - "src/**"
      - "examples/**"
      - "pyproject.toml"
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/tests.yaml"
      - "src/**"
      - "examples/**"
      - "pyproject.toml"

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.12", "3.13"]

    defaults:
      run:
        shell: bash

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install project dependencies
        run: |
          uv sync --all-groups --all-extras

      - name: Run linting (Ruff)
        run: |
          uv run ruff check src examples
          uv run ruff format --check src examples

      - name: Run type checking (MyPy)
        run: |
          uv run mypy src

      # for the future, if tests are written
      # - name: Run tests
      #   run: |
      #     uv run pytest tests
